### PR TITLE
Release/v20.2.0

### PR DESCRIPTION
**Pull request by UDLD**
# [v20.2.0](https://github.com/citahub/cita-sdk-java/compare/v1.0.0...v20.2.0) (2020-02-17)

Hi, folks.

Today,  CITA-SDK-JAVA released version 20.2.0. In this version, we adopt a new version naming rule, that is, the version command method of **YY.MM. X**, where **YY** represents year, **MM** represents month, and **X** represents bug fix version number.

>Why the new version rule?
>Community version CITA uses new version command method of **YY.MM. X**, where **YY** represents year, **MM** represents month, and **X** represents bug fix version number. In order to adapt to community version CITA, the community version of CITA-SDK-JAVA will use the version naming rules of **Year.Month. X**, which is similar to the version rules of Ubuntu.

***

今天，CITA-SDK-JAVA 发布 20.2.0 版本。在这个版本中，我们采用了新的版本命名规则，即采用 **YY.MM.X** 的版本命令方法，**YY** 表示年，**MM** 表示月，**X** 表示修订号。

> 为什么采用新的版本规则？
> 社区版CITA 使用 **YY.MM. X** 新版命名方法，为了适应社区版CITA，CITA-SDK-JAVA 的社区版本将启用 **年.月.X** 的版本命名规则，这有点类似 Ubuntu 的版本规则。

***

### Added

* add gradle cache in travis ci

### Changed

* change cryptape to citahub in tests module

### Documented

* show license and tag badges in README
* change cryptape to citahub in CHANGELOG

### CODE REVIEW

**Review by yangzhenlong — APPROVED** [review]

**Review by rainchen — CHANGES_REQUESTED** [review]
PR title is not matching with the base branch name

**Review by rainchen — CHANGES_REQUESTED** [review]
should add tests against CITA v20.2.0

**Comment by UDLD** [comment]
> should add tests against CITA v20.2.0

ok wait some minites

**Comment by rainchen** [comment]
develop branch is updated, please rebase this PR branch

**Comment by UDLD** [comment]
> should add tests against CITA v20.2.0

@rainchen 

测试结论： PASS
https://ci.devops.rivtower.com/view/cita-sdk-system-testing-pipeline/job/run-cita-java-sdk-test/104/test-report/

**Comment by UDLD** [comment]
> develop branch is updated, please rebase this PR branch

@rainchen  have rebases and CII pass

**Comment by rainchen** [comment]
@UDLD 

about the release notes:

> change cryptape to citahub in tests module

this is not a "Added" change, this is a "Changed" change

**Comment by UDLD** [comment]
> @UDLD
> 
> about the release notes:
> 
> > change cryptape to citahub in tests module
> 
> this is not a "Added" change, this is a "Changed" change

@rainchen  fixed and CI passed, please review

**Review by rainchen — APPROVED** [review]

**Pull request merged**
